### ISSUE TITLE
phpstan

### ISSUE THREAD

**Issue by TomHAnderson** [Ecodev/graphql-doctrine#15]
The new(er) tool phpstan/phpstan could be used on this repository to improve the code.

I don't feel I have the breath of knowledge to correct the 33 errors it finds with --level=7 so I'm just putting in this suggestion.

**Comment by PowerKiKi** [comment]
Thanks for letting me know. We already use scrutinizer for similar purpose, but it might interesting to experience with phpstan too. I'll try to give it a try at some point...
