### ISSUE TITLE
Some usage issues

### ISSUE THREAD

**Issue by coolg54321** [Ecodev/graphql-doctrine#18]
First of all thank you so much for this amazing library! because of this now so easy to switch to GraphQL from REST API with in few minutes.

I have few newbie niggles with the library,

1. I feel there is no proper documentation on how to write sorting and filter queries. I tried to figure it out from the examples and I managed to understand sorting but not the filters yet.

I could sort DESC by age by

```graphql
query {
	Employee (sorting: { field: age, order: DESC }) {
      name
      age
      address
      city
      cTime
    }
}
```

Not sure how i can also filter by employees of age between 18 and 55? I have tried several weird things such as

```graphql
query {
	Employee (sorting: { field: age, order: DESC }, filter: { conditions: { age : { between: { 18 55 } }  } }) {
      name
      age
      address
      city
      cTime
    }
}

```

2. Is it possible to do doctrine joins with some table with GraphQL query with this library? can you please provide an example
3. I saw it is possible to add custom sorting and filtering from the blog example but is it possible to get this field in the response as well?

Thanks in advance!

**Comment by PowerKiKi** [comment]
I strongly suggest to work with [ChromeiQL](https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij) (or equivalent) when writing queries to benefit from auto-completion.

1. Filtering with `between`, you missed the keys `groups`, `from`, and `to`:

```graphql
query {
    Employee (sorting: { field: age, order: DESC }, filter: {groups: [{conditions: {
        age: {between: {from: 18, to: 55}}
    }}]}) {
        name
        age
    }
}
```

2. Yes you can do join, but only on relations known by Doctrine (assuming a `Company` entity exists):

```graphql
query {
    Employee(filter: {groups: [{joins: {company: {conditions: [{name: {like: {value: "%foo%"}}}]}}}]}) {
        name
        age
    }
}
```

3. If you write a custom sort/filter by computing something, then you'll have to do some extra work to expose that computed value in your entity getter. You probably want to organize things to re-use the same code for both the getter and the custom sort/filter.

You may want to have a look in https://github.com/Ecodev/dilps/tree/master/server/Application/Api/Input. I don't think there is exactly what you need, but it's a real-world application using this lib.

Also I strongly suggest to browse the test data that cover a lot of common use-cases: https://github.com/Ecodev/graphql-doctrine/tree/master/tests/data/query-builder

**Comment by PowerKiKi** [comment]
Oh, of course PR to improve the documentation are more than welcome. Some sections, such as filter and sorting, were written rather quickly. It would help to have an external point of view such as yours. Feel free to open a PR with your ideas as a starting point and it can then be improved together.

**Comment by coolg54321** [comment]
Wow, thank you so much for your quick response. This would really help go in the right direction.

Sure, I am planning to this library more in our current application, I'm sure I would be able to contribute to the documentation soon once I have the more understanding of it.

Thank you so much once again!
