### ISSUE TITLE
Hello, could you give me a demo?

### ISSUE THREAD

**Issue by StasToken** [Ecodev/graphql-doctrine#32]
Hello, I was pushed by the fact that there is very little documentation on the Internet on this subject, and I had difficulties with studying, could you throw a demo example of a simple implementation on symfony 4 or at least start writing wiki ?

**Comment by PowerKiKi** [comment]
You might want to have a look at https://webonyx.github.io/graphql-php/ as this package heavily rely on graphql-php. For this package in particular, the readme should cover the basics to get you started.

If that's not enough you can have a look at a real world project: https://github.com/Ecodev/my-ichtus

But I have nothing available with Symfony, nor will I be able to create a demo for that.
