### ISSUE TITLE
No type registered with key `date`. Either correct the usage, or register it in your custom types container when instantiating `GraphQL\Doctrine\Types`

### ISSUE THREAD

**Issue by theoaks** [Ecodev/graphql-doctrine#33]
My model has a column with type date. This is causing it to fail.

GraphQL\Doctrine\Exception: No type registered with key `date`. Either correct the usage, or register it in your custom types container when instantiating `GraphQL\Doctrine\Types`. in C:\Projects\ea_api\vendor\ecodev\graphql-doctrine\src\Types.php on line 162

**Comment by PowerKiKi** [comment]
You need to implement and register a custom type. This is explained in https://github.com/Ecodev/graphql-doctrine#custom-types

**Comment by theoaks** [comment]
> You need to implement and register a custom type. This is explained in https://github.com/Ecodev/graphql-doctrine#custom-types

I'm aware of that and I'm already using the same code to register DateTime, but it doesn't seem to work for type: date which, in doctrine is not the same as type: datetime

**Comment by PowerKiKi** [comment]
You need to register a type with the `"date"` key. If you want more help, you'll have to show what you are doing in more details.

**Comment by theoaks** [comment]
Here's the code

```php
use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\DBAL\Types\DateType;
use EA\Db\Investment\LiabilityPlacement;
use GraphQL\Doctrine\DefaultFieldResolver;
use GraphQL\Doctrine\Types;
use GraphQL\GraphQL;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Schema;
use UCAP\Lib\DatabaseHelper;
use Zend\ServiceManager\ServiceManager;

require DIR . '/vendor/autoload.php';
ini_set('expose_php', 'off');
define("ASSETS_BASE_DIR", "");

oaks_load_models(dirname(FILE) . '/db-entities');

$custom_types = new ServiceManager([
'invokables' => [
DateTime::class => DateTimeType::class,
'date' => DateType::class,
]
]);

$types = new Types(DatabaseHelper::getEntityManager(), $custom_types);

GraphQL::setDefaultFieldResolver(new DefaultFieldResolver());

$schema = new Schema([
'query' => new ObjectType([
'name' => 'query',
'fields' => [
'placements' => [
'type' => Type::listOf($types->getOutput(LiabilityPlacement::class)),
'args' => [
[
'name' => 'filter',
'type' => $types->getFilter(LiabilityPlacement::class), // Use automated filtering options
],
[
'name' => 'sorting',
'type' => $types->getSorting(LiabilityPlacement::class), // Use automated sorting options
],
],
'resolve' => function ($root, $args) use ($types) {
$queryBuilder = $types->createFilteredQueryBuilder(LiabilityPlacement::class, $args['filter'] ?? [], $args['sorting'] ?? []);

                return $queryBuilder->getQuery()->getResult();
            }
        ]
    ]
])
]);
```

This happens when I fix the DateType:

Fatal error: Uncaught Error: Call to private Doctrine\DBAL\Types\Type::__construct() from context 'Zend\ServiceManager\Factory\InvokableFactory' in C:\Projects\ea_api\vendor\zendframework\zend-servicemanager\src\Factory\InvokableFactory.php on line 30

Looks like the constructor is private

**Comment by PowerKiKi** [comment]
You are using DBAL types, not GraphQL types. You have to write your own type implementation and do something like that:

```diff
- use Doctrine\DBAL\Types\DateTimeType;
- use Doctrine\DBAL\Types\DateType;
+ use MyApplication\MyCustomGraphQLTypes\DateTimeType;
+ use MyApplication\MyCustomGraphQLTypes\DateType;
```

**Comment by theoaks** [comment]
It works now... Is there support for doctrine `object` and `json` data types? I can't seem to get it to work

**Comment by PowerKiKi** [comment]
See here for a list of built-in types:

https://github.com/Ecodev/graphql-doctrine/blob/55a1216dfadd324dbfcc4aec8c6e86cc58bbedfa/src/Types.php#L407-L430

**Comment by theoaks** [comment]
> See here for a list of built-in types:
> 
> https://github.com/Ecodev/graphql-doctrine/blob/55a1216dfadd324dbfcc4aec8c6e86cc58bbedfa/src/Types.php#L407-L430

Is there any plan to support those types?

**Comment by PowerKiKi** [comment]
No there is no plan. Only the application can know the expected structure of json and object. It cannot be guessed by the lib. So a custom types must be written in the application.

**Comment by theoaks** [comment]
> No there is no plan. Only the application can know the expected structure of json and object. It cannot be guessed by the lib. So a custom types must be written in the application.

Understood... Is there an ignoreTypes parameter in the type mapper? This way, I can instruct the mapper to ignore those data types.

**Comment by PowerKiKi** [comment]
GraphQL is strongly typed. You cannot ignore types. But you can define as many custom types as you want and make them as flexible as you need and use them where necessary. But if you go for unstructured blob of data, that might go against GraphQL ideas...

**Comment by theoaks** [comment]
> GraphQL is strongly typed. You cannot ignore types. But you can define as many custom types as you want and make them as flexible as you need and use them where necessary. But if you go for unstructured blob of data, that might go against GraphQL ideas...

I understand. What I'm saying is that when the mapper is traversing the entities in the Entity Manager in order build the schema, it should be able to skip certain fields... An annotation I can add to the property should do

**Comment by PowerKiKi** [comment]
See https://github.com/Ecodev/graphql-doctrine#exclude-a-field
