### ISSUE TITLE
Getting entity fields with magic methods

### ISSUE THREAD

**Issue by khrizt** [Ecodev/graphql-doctrine#37]
Hi,

I'm implementing graphql with doctrine and I found a "corner case" where the library is not able to obtain the value of the entity. I'm implementing my entities with private fields and a `__get` magic method, something like this:

```php
class Entity {
    private string $name = "Name";
    
    public function __get(string $name)
    {
        if (!property_exists($this, $name)) {
            throw new InvalidArgumentException();
        }

        return $this->$name;
    }
}
```

But the `DefaultFieldResolver` [has this checking](https://github.com/Ecodev/graphql-doctrine/blob/master/src/DefaultFieldResolver.php#L60) that makes null the value:

```php
if (isset($source->{$fieldName})) {
```

In this case isset returns false, but `$source->{$fieldName}` returns a valid value. `empty` function won't work neither, the only thing that could work is doing isset with the value returned, but I don't know if this is a proper solution.

Have you ever found a similar case or is there a better solution for this case?

Thanks

EDIT: I've solved this in my fork modifying the line I was talking about with this one:

```php
if (isset($source->{$fieldName}) || method_exists($source, '__get')) {
```
I'm not sure if this a recommendable solution, haven't found a lot of documentation on how to do somehting like that, but I wanted to leave it here. Thanks again

**Comment by PowerKiKi** [comment]
As you found out __get magic method is not supported and I wouldn't
recommend it.

If you don't have getter methods, then this lib cannot auto discover
GraphQL fields, and you cannot customize fields via annotation. You'd lose
a lot of benefits this lib can bring by using magic methods. I'm probably
never going to support it in the lib itself.

All that being said, you should be able to solve your issue by
implementing, and using, your own implementation of field resolver. That
shouldn't be too much work.

But if you don't have have getter, does that mean you also don't have
setter ? Then do you build GraphQL types manually for each entity?

**Comment by khrizt** [comment]
I did solve the issue, but I was just wondering if as php 7.4 has type hinting in class properties maybe Reflection could be used to get the type from the property itself instead of using getters and setters.

I don't have getters and setters in entities because I try to avoid [anemic domain models](https://martinfowler.com/bliki/AnemicDomainModel.html) and about the types I have a factory class that generates the type for each entity, but I was thinking that they could inferred from entities' properties also. If you think that could be a way to consider I can try and do a PR.

**Comment by PowerKiKi** [comment]
Type hinting class properties is something I look forward to. But right now we are not using that, and probably won't for some time. Instead we heavily rely on getter/setter. This is also convenient to expose getters that do not map directly to a property. In general they give some welcomed flexibility.

So I am not even sure that supporting typed properties, instead of getters, would be the way to go for us.
