### ISSUE TITLE
Problem when using with "doctrine/doctrine-bundle"

### ISSUE THREAD

**Issue by emaslak** [Ecodev/graphql-doctrine#56]
First of all thanks for all the effort made to develop this bundle!

My problem is that when i try to use this bundle together with `doctrine/doctrine-bundle` it doesn't work because of error:
```
graphql-doctrine requires Doctrine to be configured with a `Doctrine\\Persistence\\Mapping\\Driver\\AnnotationDriver`.
```

After some digging I found that `doctrine/doctrine-bundle` implemented decorator for metadriver implementation (https://github.com/doctrine/DoctrineBundle/commit/a1268d43a0e0e469f76bc9c027db33b23050c837#diff-0c1c41fb2c90d9d15f9c9bf6b9e4543221b239e048c1dde8b8c71bb58d13cec5) which causes `\GraphQL\Doctrine\Factory\AbstractFactory::getAnnotationReader` to fail.

At the moment I solved it with following hackaround:
```
$actualMetadataDriver = $this->entityManager->getConfiguration()->getMetadataDriverImpl()->getDriver();
$this->entityManager->getConfiguration()->setMetadataDriverImpl($actualMetadataDriver);
$types = new Types($this->entityManager, $this->getCustomTypes());
```
Maybe there are other (more proper) ways to make bundle work with newest `doctrine/doctrine-bundle`?

Also one more side question: maybe you could give any advise on how to test code where `\GraphQL\Doctrine\Types` class is used? It's final, doesn't have any interface and expects `Doctrine\ORM\EntityManager` and not its interface so I'm not sure how to mock it.

Thanks in advance!

**Comment by PowerKiKi** [comment]
I am not familiar with `doctrine/doctrine-bundle`, but it doesn't seems there'd be a better way to workaround that for now. I am wondering if your application still work as intended, because AFAIK you entirely "cancel" the custom decorator... would that not make some things fail in `doctrine/doctrine-bundle` ?

As for the tests, I guess we could create an interface for `\GraphQL\Doctrine\Types`, but first I'd like to understand better your use-case. I've never have the need to mock this class. What kind of test are you writing ? Where does this class is used that makes you want to mock it ?

**Comment by emaslak** [comment]
Thanks for the answer! 

> would that not make some things fail in doctrine/doctrine-bundle

It will disable `CustomIdDecorator`, but as I'm not using it at the moment it should not be a problem. But might be in the future. We'll see :)

> I'd like to understand better your use-case

I have written `TypesBuilder` which has method `getTypes` which returns `Types` instance. Also I have `FieldsBuilder` which builds different fields for my GQL Query. Types builder is being injected into `FieldsBuilder` and types are assigned to private variable. As there is no interface I can't mock `Types` object :(

```
class FieldsBuilder implements FieldsBuilderInterface
{
    private Types $types;
    ...
    public function __construct(
        ...
        TypesBuilderInterface $typesBuilder,
    )
    {
        $this->types = $typesBuilder->getTypes();
    }
    ...
}

**Comment by PowerKiKi** [comment]
Could give a try to https://github.com/Ecodev/graphql-doctrine/pull/57 and see if it would solve your use-case ?

**Comment by emaslak** [comment]
Sorry for such long answering time and huge thanks for such fast support :) Finally tested it and yes, `TypesInterface` totally solves my problem with tests! :)

**Comment by emaslak** [comment]
Hi @PowerKiKi, just wanted to know if https://github.com/Ecodev/graphql-doctrine/pull/57 will be released anytime soon? :)

**Comment by PowerKiKi** [comment]
Here you go: https://github.com/Ecodev/graphql-doctrine/releases/tag/7.2.0

**Comment by emaslak** [comment]
Thank you!
