### ISSUE TITLE
Support for non-empty constructor of custom types

### ISSUE THREAD

**Issue by octaharon** [Ecodev/graphql-doctrine#6]
Right now it seems impossible to define a custom object type, which includes another custom object type, because it requires passing TypeRegistry as a parameter to the type constructor or having its methods statically available. I.e.

```php
 class MyCustomType extends ObjectType
 {
     public function __construct(TypeRegistry $types)
     {
         parent::__construct([
                 'description' => 'Something ',
                 'fields' => [
                     'listOfSomething' => [
                         'type' => Type::listOf($types->get('OtherCustomObjectType')
                     ]
                 ]
             ]
         );
     }
```

Implying that "OtherCustomObjectType" is also used elsewhere in API so can't be declared inline.

Since all the class management is done internally, it's not possible to bypass implemented object creation routine. I suggest either making Types::registerInstance a public method, or allowing passing a class instance as type definition instead of just name to Types::get

**Comment by PowerKiKi** [comment]
What about supporting instance of types in `$customTypeMapping` argument of `Types::__construct()` ? Would that solve your use-cases ?

**Comment by octaharon** [comment]
No, because custom GraphQL Type doesn't necessary have any related PHP type. For instance I have a mutation which returns two lists of different entities, so for response say I will have some shape like 
{ posts:[Post], comments:[Comment]}
and I am definitely not creating a class for that structure, but instead returning an associative array or an stdClass instead, Still I have to define a type for GraphQL Layer for it to work properly.

That might be a bad example, since creating this kind of structure as a class is not that big of an effort, but right now I have a necessity to operate almost arbitratry JSON objects received from 3rd party API inside my GraphQL API, without actually having any server-side structure for them - that what causes me to create fancy complex types and that's when a problem arises

**Comment by PowerKiKi** [comment]
The map is internally used as `$customTypeMapping as $phpType => $graphQLType`, but here `$phpType` (the map key) does not have to be an actual PHP class name, it can be any arbitrary string. It has been documented as "PHP type" because it was the use-case we thought about, but if it can fit your use-case, we could re-word the documentation to make it more clear.

So you could do something like:

```php
$mapping = [
    DateTime::class => DateTimeType::class,
    'foo' => new CustomObjectType($whatever),
    'bar' => new OtherCustomObjectType($whatever),
];

$types = new Types($entityManager, $mapping);

// Build schema...
```

Wouldn't that work ?

**Comment by octaharon** [comment]
This particular thing will not work since to get a type definition for a dependent type (OtherCustomObjectType) inside a "master" type (CustomObjectType in this example) I have to make a call to $types->get, so I need to pass an instance of TypeManager, which is not instantiated at the moment of creating the type instance given that syntax the module is providing. So basically it's a circular reference problem, and I don't see a way to instantiate a secondary type lazily. Static calls would have solved that

But I've tried several similar tricks, most of them lead to an API layer failing because either of one of those types being declared more than once or "Not a doctrine entity" error

Also the secondary problem is that I can't use those types as an input type because it's explicitly prohibited by `$this->throwIfNotEntity($className);`

**Comment by octaharon** [comment]
So as a temporary workaround what I did is creating my own higher-level TypeManager which has type definitions accessible statically, the problem though is that I need to pass `EntityManager` into the module's `Types` non-statically. and, since I can't use DI or whatsoever, it can cause a race condition error, when a certain _custom type_ is referenced in the `@Field` annotation of an entity, whose "type" is being requested from `Type::get` prior to that _custom type_ itself being registered within it.  

And for `Input` type I had to pass a custom hack into `Types` constructor like this
`CustomGraphQLType::class . 'Input' => CustomGraphQLType::class`
which is very dirty :)

Anyhow it seems to work, but I really hope you'll come up with some cleaner and more predictable solution, or at least document this use case so others can find a way to do it too.

**Comment by PowerKiKi** [comment]
I still don't have too much time to spend on this, but I wonder if something like the PSR-11 container interface could help us with this case...

In the meantime, if you can create a [MCVE](https://stackoverflow.com/help/mcve) that expose your original issue, and another one with your current workaround, that could help further the discussion.

**Comment by PowerKiKi** [comment]
So I went ahead and implemented https://github.com/Ecodev/graphql-doctrine/commit/77b356ac79abd425bf53634fc539f2fb6c636d26. I believe it should solve pretty much any cases you might have. Let me know how it goes for you.
